version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crud

  api:
    build: .
    ports:
      - "7777:7777"
    depends_on:
      - postgres
    environment:
      - DB_HOST:postgres
      - DB_PORT:5432
      - DB_USERNAME:postgres
      - DB_PASSWORD:admin
      - DB_NAME:crud